name: Markdown Link Check
on:
  pull_request:
  push:
    branches: [main]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: yes
          folder-path: "."
          file-path: "README.md"
          config-file: ".mlc_config.json"
